# Generated by Django 4.2 on 2023-04-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('locality', models.CharField(max_length=200, verbose_name='Место')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('mobile', models.IntegerField(default=0, verbose_name='Мобильный телефон')),
                ('zipcode', models.IntegerField(verbose_name='Индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('selling_price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(verbose_name='Скидка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('composition', models.TextField(default='', verbose_name='Состав')),
                ('prodapp', models.TextField(default='', verbose_name='Продукт')),
                ('category', models.CharField(choices=[('CR', 'Творог'), ('ML', 'Молоко'), ('LS', 'Ласси'), ('MS', 'Коктейль'), ('PN', 'Панир'), ('GH', 'Топленое масло'), ('CZ', 'Сыр'), ('IC', 'Мороженое')], max_length=2, verbose_name='Категории')),
                ('product_image', models.ImageField(upload_to='product', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заказ')),
                ('razorpay_order_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заказ по статусу')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оплата')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('Accepted', 'Принимается'), ('Packed', 'Подготовлен к отправке'), ('On the Way', 'В пути'), ('Delivered', 'Доставлен'), ('Cancel', 'Отменен'), ('В ожидании', 'В ожидании')], default='В ожидании', max_length=50, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель')),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.payment', verbose_name='Оплата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Место заказа',
                'verbose_name_plural': 'Место заказов',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
